test the change for different enviromment

diff --git a/.github/actions/setup/setup-build-env/action.yml b/.github/actions/setup/setup-build-env/action.yml
--- a/.github/actions/setup/setup-build-env/action.yml
+++ b/.github/actions/setup/setup-build-env/action.yml
@@ -15,52 +15,54 @@ inputs:
   ENV_BETA:
     description: 'Environment variable for beta'
   ENV_DEV:
-    description: 'Environment variable for DEVS'
+    description: 'Environment variable for development'
+  ENVIRONMENT:
+    description: 'Environment to build for'
 runs:
   using: composite
   steps:
-  - name: Create .env file
-    shell: bash
-    run: |
-      ENVIRONMENT="${{ env.ENVIRONMENT }}"
+    - name: Create .env file
+      shell: bash
+      run: |
+        ENVIRONMENT="${{ env.ENVIRONMENT }}"
 
-      if [[ "$ENVIRONMENT" == "production" ]]; then
-        ENV_CONTENT="${{ inputs.ENV_PROD }}"
-      elif [[ "$ENVIRONMENT" == "staging" ]]; then
-        ENV_CONTENT="${{ inputs.ENV_STAGING }}"
-      elif [[ "$ENVIRONMENT" == "development" ]]; then
-        ENV_CONTENT="${{ inputs.ENV_DEV }}"
-      elif [[ "$ENVIRONMENT" == "beta" ]]; then
-        ENV_CONTENT="${{ inputs.ENV_BETA }}"
-      else
-        echo "Unknown environment: $ENVIRONMENT" >&2
-        exit 1
-      fi
-
-      # Create the .env file
-      ENV_FILE="${{ github.workspace }}/configuration/.env.$ENVIRONMENT"
-      echo "$ENV_CONTENT" > "$ENV_FILE"
-      echo "ENVFILE=$ENV_FILE" >> $GITHUB_ENV
-
-      # Check if the .env file was created
-      if [[ -f "$ENV_FILE" ]]; then
-        echo ".env file created successfully: $ENV_FILE"
-        
-        # Verify the content of the .env file
-        FILE_CONTENT=$(<"$ENV_FILE")
-        if [[ "$FILE_CONTENT" == "$ENV_CONTENT" ]]; then
-          echo "The .env file has the correct content."
-          echo "Content of the .env file:"
-          echo "$FILE_CONTENT"  # Show the content of the .env file
+        if [[ "$ENVIRONMENT" == "production" ]]; then
+          ENV_CONTENT="${{ inputs.ENV_PROD }}"
+        elif [[ "$ENVIRONMENT" == "staging" ]]; then
+          ENV_CONTENT="${{ inputs.ENV_STAGING }}"
+        elif [[ "$ENVIRONMENT" == "development" ]]; then
+          ENV_CONTENT="${{ inputs.ENV_DEV }}"
+        elif [[ "$ENVIRONMENT" == "beta" ]]; then
+          ENV_CONTENT="${{ inputs.ENV_BETA }}"
         else
-          echo "The .env file does not have the expected content." >&2
+          echo "Unknown environment: $ENVIRONMENT" >&2
           exit 1
         fi
-      else
-        echo "Failed to create .env file: $ENV_FILE" >&2
-        exit 1
-      fi
 
+        # Create the .env file
+        ENV_FILE="${{ github.workspace }}/configuration/.env.$ENVIRONMENT"
+        echo "$ENV_CONTENT" > "$ENV_FILE"
+        echo "ENVFILE=$ENV_FILE" >> $GITHUB_ENV
+
+        # Check if the .env file was created
+        if [[ -f "$ENV_FILE" ]]; then
+          echo ".env file created successfully: $ENV_FILE"
+          
+          # Verify the content of the .env file
+          FILE_CONTENT=$(<"$ENV_FILE")
+          if [[ "$FILE_CONTENT" == "$ENV_CONTENT" ]]; then
+            echo "The .env file has the correct content."
+            echo "Content of the .env file:"
+            echo "$FILE_CONTENT"  # Show the content of the .env file
+          else
+            echo "The .env file does not have the expected content." >&2
+            exit 1
+          fi
+        else
+          echo "Failed to create .env file: $ENV_FILE" >&2
+          exit 1
+        fi
+      shell: bash
 
     - name: Set build directory
       id: set_build_dir
@@ -77,10 +79,10 @@ runs:
 
     - name: Set artifact name
       id: set_artifact_name
+      shell: bash
       run: |
         ARTIFACT_NAME="${{ env.ENVIRONMENT }}-build-${{ github.sha }}"
         echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
-      shell: bash
 
     - name: Set gradlew permissions
       if: ${{ env.PLATFORM == 'android' }}
